[device]
# Asahi Alarm uses wpa_supplicant by default since version 2.12+ contains an Asahi fix - see:
# https://gitlab.archlinux.org/archlinux/packaging/packages/wpa_supplicant/-/merge_requests/4
#wifi.backend=iwd
